# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to convert a VCF file to a binary dosage file for GxEScan
#' 
#' Function to convert a VCF file to a binary dosage file for GxEScan. 
#' The binary formatted file is smaller that the VCF file and reads in much quicker.
#' 
#' @param vcfFilename
#' Name of VCF file
#' @param outBaseFilename
#' Base filename of output files. Three files are output.
#' A family file with extension .fam.
#' A map file with extension .bim.
#' A binary dosage file with extenstion .bdosage.
#' @param initSub
#' Amount of memory to allocate for subjects. Should be the number of subjects.
#' Additional memory will be allocated if not enough is initially allocated.
#' Having to do this can slow down the speed of the routine because of memory
#' allocations/deallocations.
#' @return
#' 0 success
#' 1 failure
#' @importFrom Rcpp evalCpp
#' @useDynLib GxEScanR
#' @export
VCF_to_BinaryDosage <- function(vcfFilename, outBaseFilename, initSub) {
    .Call('BinaryDosageFiles_VCF_to_BinaryDosage', PACKAGE = 'BinaryDosageFiles', vcfFilename, outBaseFilename, initSub)
}

#' Function to extract SNPs from a binary dosage file
#' 
#' Function to extract SNPs from a binary dosage file
#' 
#' @param bdosageFilename
#' Name of binary dosage file
#' @param mapFilename
#' Name of map file associated with dosage file
#' @param numSub
#' Number of subjects with data in dosage file
#' @param numSNPs
#' Number of SNPs to read in
#' @return
#' List with a vector of dosages and a matrix of probabilities
#' and a list of the input values
#' @importFrom Rcpp evalCpp
#' @useDynLib GxEScanR
#' @export
ExtractDosages <- function(bdosageFilename, mapFilename, numSub, numSNPs) {
    .Call('BinaryDosageFiles_ExtractDosages', PACKAGE = 'BinaryDosageFiles', bdosageFilename, mapFilename, numSub, numSNPs)
}

#' Function to extract more SNPs from a binary dosage file
#' 
#' Function to extract more SNPs from a binary dosage file
#' 
#' @param inputs
#' List of inputs returned from ExtractDosages
#' @return
#' List with a vector of dosages and a matrix of probabilities
#' and a list of the input values
#' @importFrom Rcpp evalCpp
#' @useDynLib GxEScanR
#' @export
ExtractMoreDosages <- function(inputs) {
    .Call('BinaryDosageFiles_ExtractMoreDosages', PACKAGE = 'BinaryDosageFiles', inputs)
}

